# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-signon

# >> macros
# << macros

Summary:    Signon framework support for QML applications
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-signon
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-signon.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(libsignon-qt)
Provides:   nemo-qml-plugins-signon > 0.3.17
Obsoletes:   nemo-qml-plugins-signon <= 0.3.17

%description
%{summary}.

%package signon-tests
Summary:    QML signon plugin tests
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description signon-tests
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/signon/libnemosignon.so
%{_libdir}/qt4/imports/org/nemomobile/signon/qmldir
# >> files
# << files

%files signon-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/signon/*
# >> files signon-tests
# << files signon-tests
