# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       nemo-qml-plugin-signon-qt5

# >> macros
# << macros

Summary:    Signon framework support for QML applications
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-signon
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-signon-qt5.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(libsignon-qt5)

%description
%{summary}.

%package signon-tests
Summary:    QML signon plugin tests
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description signon-tests
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/qt5/qml/org/nemomobile/signon/libnemosignon.so
%{_libdir}/qt5/qml/org/nemomobile/signon/qmldir
# >> files
# << files

%files signon-tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins-qt5/signon/*
# >> files signon-tests
# << files signon-tests
